services:
  postgres:
    image: postgres:16
    container_name: postgres_health_monitoring
    environment:
      POSTGRES_DB: health-monitoring-system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hms@1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
