server:
  port: 8081
spring:
  application:
    name: ms-user
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
#    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/health-monitoring-system-users
    username: postgres
    password: Hms@1234
    jpa:
      hibernate:
#        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true
    output:
      ansi:
        enabled: Always
  eureka:
    client:
      serviceUrl:
        defaultZone: 'http://localhost:8761/eureka'
    instance:
      hostname: localhost

#  Configuracao do BROKER
  rabbitmq:
    host: jackal.rmq.cloudamqp.com
    port: 5672
    username: rxhkchqs
    password: w-e2eaFKg-hkRskiJ0Hw_E1k1kJerniG
    virtual-host: rxhkchqs
