server:
  port: 8082
  servlet:
    context-path: '/ms-patient/'

spring:
  application:
    name: ms-patients
  datasource:
    url: jdbc:postgresql://localhost:5432/health-monitoring-system
    username: postgres
    password: Hms@1234
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always

  #  Configuracao do BROKER
  rabbitmq:
    host: jackal.rmq.cloudamqp.com
    port: 5672
    username: rxhkchqs
    password: w-e2eaFKg-hkRskiJ0Hw_E1k1kJerniG
    virtual-host: rxhkchqs

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost